### ISSUE TITLE
Problem with musoQuickEffect

### ISSUE THREAD

**Issue by dlgiu** [hollorol/RBBGCMuso#5] opened 2019-01-25 12:45 UTC
## Description

In quickeffect the parameter values are rounded to the second decimal places. In some cases 4 decimal places would be needed. For example if you provide 0.00-0.05 values for fraction of leaf N in PEP, the simulation is running only 6 times.

## How to reproduce the bug

musoQuickEffect(calibrationPar = 62, startVal = 0, endVal = 0.05, nSteps = 10, outVar = 3009)

**Comment by hollorol** [comment] 2019-01-28 10:02
# Reason of the bug
In the paramSweep function I generate categories with rounding to 2 decimals. The reason was pure aesthetics. 
# Possibilities for dynamic rounding
1. Using the fact that if we divide 1 by 1 ... 9 numbers the results will be unique within 2 decimal point, we can get the optimal rounding factor by counting the number of digits behind the decimal point of the range length (in this case 0.05), and adding 2 to this number. 
2. Using a while loop, and the unique, length function to get the smallest number for rounding which produce exactly nStep (in this case 10) unique value. 

I found the first solution more elegant, but it has 2 drawbacks: by design it can use more digits than the second solution, and for my surprise the second solution is a little bit faster (see the table bellow, wich contains the result of microbenchmark, where the total number of testruns was 100 and the values are in microseconds).

I have chosen the second implementation.  The 0.6.1.3 patch version will be dedicated to this bug.
  

| expr      |    min |     lq |     mean |  median |      uq |     max | neval | cld |
|-----------|--------|--------|----------|---------|---------|---------|-------|-----|
| dynRound1 | 82.426 | 83.774 | 87.95883 | 84.3595 | 85.1800 | 152.772 |   100 | b   |
| dynRound2 | 56.800 | 59.390 | 69.62173 | 61.1105 | 62.5535 | 397.201 |   100 | a   |

**Comment by hollorol** [comment] 2019-01-28 10:40
I close this issue since RBBGCMuso 0.6.1.3 is out, so the bug is solved.

**Closed by hollorol** 2019-01-28 10:40 UTC
Labels: bug
